name: Publish

on:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VERSION: 3.9

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Update base dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U setuptools wheel

      - name: Check version
        run: |
          tag_version="${GITHUB_REF#refs/tags/v}"
          project_version="$(python3 setup.py --version)"
          if [ "$tag_version" != "$project_version" ]; then
            echo "Version mismatch"
            echo "Tag version: $tag_version"
            echo "Project version: $project_version"
            exit 1
          fi

      - name: Install PyPA build
        run: python3 -m pip install -U build

      - name: Build source and wheel distributions
        run: |
          python3 -m build --sdist --wheel --outdir dist/ .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
